#%RAML 1.0 Trait
usage: Apply this trait to enforce client_id identification.
headers:
  client-id:
    type: string
    description: Client Id to authenticate to system API
    required: true
  client-secret:
    type: string
    description: Client Secret to authenticate to system API
    required: true